### ISSUE TITLE
Issue trying to start after install

### ISSUE THREAD

**Issue by kirkins** [1j01/hacky-game#1]
```
[kirkins@philip-pc hacky-game]$ npm start

> hacky-game@0.0.0 start /home/kirkins/tmp/hacky-game
> nwbuild -v 0.12.3 -r game

(node:4770) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Using v0.12.3
Create cache folder in /home/kirkins/tmp/hacky-game/node_modules/nw-builder/cache/0.12.3
Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-linux-x64.tar.gz
  downloading [====================] 100% 0.0s

Launching App
{ Error: spawn EACCES
    at exports._errnoException (util.js:1033:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:386:9)
    at /home/kirkins/tmp/hacky-game/node_modules/nw-builder/lib/index.js:716:43
    at Promise._execute (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/promise.js:79:10)
    at NwBuilder.runApp (/home/kirkins/tmp/hacky-game/node_modules/nw-builder/lib/index.js:715:12)
    at NwBuilder.tryCatcher (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/kirkins/tmp/hacky-game/node_modules/bluebird/js/release/promise.js:524:17) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }

npm ERR! Linux 4.4.59-1-MANJARO
npm ERR! argv "/home/kirkins/.nvm/versions/node/v7.7.2/bin/node" "/home/kirkins/.nvm/versions/node/v7.7.2/bin/npm" "start"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! hacky-game@0.0.0 start: `nwbuild -v 0.12.3 -r game`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hacky-game@0.0.0 start script 'nwbuild -v 0.12.3 -r game'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hacky-game package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nwbuild -v 0.12.3 -r game
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hacky-game
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hacky-game
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kirkins/tmp/hacky-game/npm-debug.log

```

**Comment by 1j01** [comment]
Hm, I haven't tested this on Linux, but whilst *building* is platform specific, running should work. You could try again with some changes (https://github.com/1j01/hacky-game/commit/93ede395464f469b64ab4cabd051cb2fd21529a5) that I forgot to push that actually include a major version bump of `nw-builder`, so I think there's a good chance it'll work.

**Comment by 1j01** [comment]
Nope, tried it out and I got the same error.

**Comment by 1j01** [comment]
Looks like it's [a monkey-patch I did](https://github.com/1j01/hacky-game/blob/master/monkey-patch.coffee) that breaks it. I'll check to see if that's still needed on Windows and either remove it entirely or apply it only on Windows.

Running `npm i nw-builder` fixes it (because it skips the `postinstall` step)
You'll also need to install the dependencies for the game, i.e. ` cd game ; npm i ; cd ..`

**Comment by 1j01** [comment]
I've removed the monkey patch (and added install instructions.)
Let me know if you run into any other problems or want to test out the multiplayer via hamachi :)
